apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-app

  template:
    metadata:
      labels:
        app: ai-app

    spec:
      containers:
      - name: ai-app
        image: <your-dockerhub-username>/my-ai-app:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: ai-app

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000

  selector:
    app: ai-app